<!-- Licensed under the GNU GPL-v3.0 -->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AssemblyName>KodoUpdater</AssemblyName>
    <RootNamespace>KodoUpdater</RootNamespace>

    <ApplicationIcon Condition="$([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win'))">..\..\Assets\kodo_logo.ico</ApplicationIcon>
    <ApplicationIcon Condition="'$(RuntimeIdentifier)' == '' And $([MSBuild]::IsOSPlatform('Windows'))">..\..\Assets\kodo_logo.ico</ApplicationIcon>

    <RuntimeIdentifiers>win-x64;linux-x64;linux-arm64</RuntimeIdentifiers>
    <SelfContained Condition="'$(SelfContained)' == ''">true</SelfContained>

    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>

    <Optimize>true</Optimize>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\HotfixApplyShared.cs" Link="HotfixApplyShared.cs" />
  </ItemGroup>

</Project>
